// 260729_code
// 260729_documentation

using System;

namespace TingenWebService.Core.Trove
{
    /// <summary>User-modifiable templates.</summary>
    /// <remarks>
    /// <note type="note" title="About blueprints">
    /// Blueprints are essentially templates for output generated by the Tingen Web Service. They are used to format
    /// logs,error messages, and other data in a consistent manner.<br/>
    /// <br/>
    /// When the Tingen Web Service is initialized, these templates are exported to the <c>blueprints\</c> folder.
    /// The external templates can then be modified by the user to customize the log output.
    /// </note>
    /// <note type="tip" title="Restoring blueprints">
    /// To restore a template to its original state, delete the template file from the blueprints folder and restart the
    /// Tingen Web Service. The original template will be copied back to the blueprints folder.
    /// </note>
    /// </remarks>
    internal static class BluePrint
    {
        /// <summary>Build the error log template.</summary>
        /// <returns>The error log template string.</returns>
        internal static string ErrorLogTxtBP() =>
            $"Tingen Web Service Error Log{Environment.NewLine}" +
            $"Date/Time: ~SESSION~DATE~TIME~{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"[~ERROR~CODE~]{Environment.NewLine}" +
            $"~ERROR~MESSAGE~";

        /// <summary>Build the session log template.</summary>
        /// <returns>The session log template string.</returns>
        internal static string SessLogTxtBP() =>
            $"Tingen Web Service Session Log{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"Release/Build: ~RELEASE~BUILD~{Environment.NewLine}" +
            $"Date: ~SESSION~DATE~{Environment.NewLine}" +
            $"Start: ~SESSION~START~{Environment.NewLine}" +
            $"Logged in as: ~AVATAR~USER~NAME~{Environment.NewLine}" +
            $"Avatar system: ~AVATAR~SYSTEM~{Environment.NewLine}" +
            $"Script parameter: ~SCRIPT~PARAMETER~{Environment.NewLine}" +
            $"End: ~SESSION~END~{Environment.NewLine}" +
            $"Duration: ~SESSION~DURATION~{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"Session Log{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"~SESSION~RUNNING~LOG~" +
            $"{Environment.NewLine}" +
            $"Session Details{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"~SESSION~DETAILS~{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"[End of Tingen Web Service Session Log]{Environment.NewLine}";


        /// <summary>Gets the markdown blueprint for the session log.</summary>
        /// <remars>
        /// Leave the tables like this so they end up looking as nice as possible as text.
        /// </remars>
        /// <returns>A string containing the markdown blueprint for the session log.</returns>
        internal static string SessLogMdBP() =>
            $"# Tingen Web Service Session Log{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"|                       |                                                        |{Environment.NewLine}" +
            $"|----------------------:|--------------------------------------------------------|{Environment.NewLine}" +
            $"| **Release/Build**     | ~RELEASE~BUILD~                                     |{Environment.NewLine}" +
            $"| **Date**              | ~SESSION~DATE~                                                 |{Environment.NewLine}" +
            $"| **Start**             | ~SESSION~START~                                         |{Environment.NewLine}" +
            $"| **Logged in as**      | ~AVATAR~USER~NAME~                                              |{Environment.NewLine}" +
            $"| **Avatar system**     | ~AVATAR~SYSTEM~                                                   |{Environment.NewLine}" +
            $"| **Script parameter**  | ~SCRIPT~PARAMETER~                                     |{Environment.NewLine}" +
            $"| **End**               | ~SESSION~END~                                         |{Environment.NewLine}" +
            $"| **Duration**          | ~SESSION~DURATION~                                       |{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"## Session Log{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"~SESSION~RUNNING~LOG~{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"## Session Details{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"~SESSION~DETAILS~{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"***{Environment.NewLine}" +
            $"<sub>End of Tingen Web Service Session Log</sub>{Environment.NewLine}";

        /// <returns>A string containing the html blueprint for the session log.</returns>
        internal static string SessLogHtmlBP() =>
            $"<h1>Tingen Web Service Session Log</h1>{Environment.NewLine}" +
            $"<table>{Environment.NewLine}" +
            $"<tr>{Environment.NewLine}" +
            $"<td align = \"right\"><strong>Release/Build</strong></td>{Environment.NewLine}" +
            $"<td>~RELEASE~BUILD~</td>{Environment.NewLine}" +
            $"</tr>{Environment.NewLine}" +
            $"<tr>{Environment.NewLine}" +
            $"<td align = \"right\"><strong>Date</strong></td>{Environment.NewLine}" +
            $"<td>~SESSION~DATE~</td>{Environment.NewLine}" +
            $"</tr>{Environment.NewLine}" +
            $"<tr>{Environment.NewLine}" +
            $"<td align = \"right\"><strong>Start</strong></td>{Environment.NewLine}" +
            $"<td>~SESSION~START~</td>{Environment.NewLine}" +
            $"</tr>{Environment.NewLine}" +
            $"<tr>{Environment.NewLine}" +
            $"<td align = \"right\"><strong>Logged in as</strong></td>{Environment.NewLine}" +
            $"<td>~AVATAR~USER~NAME~</td>{Environment.NewLine}" +
            $"</tr>{Environment.NewLine}" +
            $"<tr>{Environment.NewLine}" +
            $"<td align = \"right\"><strong>Avatar system</strong></td>{Environment.NewLine}" +
            $"<td>~AVATAR~SYSTEM~</td>{Environment.NewLine}" +
            $"</tr>{Environment.NewLine}" +
            $"<tr>{Environment.NewLine}" +
            $"<td align = \"right\"><strong>Script parameter</strong></td>{Environment.NewLine}" +
            $"<td>~SCRIPT~PARAMETER~</td>{Environment.NewLine}" +
            $"</tr>{Environment.NewLine}" +
            $"<tr>{Environment.NewLine}" +
            $"<td align = \"right\"><strong>End</strong></td>{Environment.NewLine}" +
            $"<td>~SESSION~END~</td>{Environment.NewLine}" +
            $"</tr>{Environment.NewLine}" +
            $"<tr>{Environment.NewLine}" +
            $"<td align = \"right\"><strong>Duration</strong></td>{Environment.NewLine}" +
            $"<td>~SESSION~DURATION~</td>{Environment.NewLine}" +
            $"</tr>{Environment.NewLine}" +
            $"</table>{Environment.NewLine}" +
            $"<br/>{Environment.NewLine}" +
            $"<h2>Session Log</h2>{Environment.NewLine}" +
            $"<para>~SESSION~RUNNING~LOG~</para>{Environment.NewLine}" +
            $"<br/>{Environment.NewLine}" +
            $"<h2>Session Details</h2>{Environment.NewLine}" +
            $"<para>~SESSION~DETAILS~</para>{Environment.NewLine}" +
            $"<br/>{Environment.NewLine}" +
            $"<hr>{Environment.NewLine}" +
            $"<p><sub>End of Tingen Web Service Session Log</sub></p>{Environment.NewLine}" +
            $"{Environment.NewLine}";
    }
}