// 251112_code
// 260515_documentation.

namespace TingenWebService.Core.Framework
{
    /// <summary>Data folder paths used by the Tingen Web Service.</summary>
    /// <remarks>
    /// Each property holds an absolute path to a specific folder in the server data directory structure.<br/>
    /// <br/>
    /// Use <see cref="Load"/> to create a populated instance for a given session context.
    /// </remarks>
    /// <seealso href="TngnWsvcDataFolders"/>
    public class TngnWsvcDataFolders
    {
        /// <summary>Avatar-generated data.</summary>
        /// <remarks>
        /// Avatar-generated data is data that is generated by Avatar (duh), and used by the Tingen Web Service.<br/>
        /// <br/>
        /// This is the only folder that is not under <c>%DataRoot%</c>, since it is shared across all Avatar systems.<br/>
        /// </remarks>
        /// <value>ex. <c>C:\Tingen_Data\AvatarGeneratedData</c></value>
        public string AvatarGeneratedData { get; set; }

        /* TODO: Maybe rename this to "SystemDataRoot" */
        /// <summary>A specific Avatar system's data.</summary>
        /// <remarks>
        /// Each Avatar system (e.g. LIVE, UAT) has its own <c>%DataRoot%</c> folder.<br/>
        /// </remarks>
        /// <value>ex. <c>C:\Tingen_Data\LIVE</c></value>
        public string DataRoot { get; set; }

        /// <summary>Application data root folder.</summary>
        /// <value>An absolute path to the <c>AppData</c> subdirectory under <see cref="DataRoot"/>.</value>
        public string AppDataRoot { get; set; }

        /// <summary>The path to the Blueprint folder.</summary>
        /// <value>An absolute path to the <c>Blueprint</c> subdirectory under <see cref="AppDataRoot"/>.</value>
        public string Blueprint { get; set; }

        /// <summary>The path to the Config folder.</summary>
        /// <value>An absolute path to the <c>Config</c> subdirectory under <see cref="AppDataRoot"/>.</value>
        public string Config { get; set; }

        /// <summary>The path to the Export folder.</summary>
        /// <value>An absolute path to the <c>Export</c> subdirectory under <see cref="AppDataRoot"/>.</value>
        public string Export { get; set; }

        /// <summary>The path to the History folder.</summary>
        /// <value>An absolute path to the <c>History</c> subdirectory under <see cref="AppDataRoot"/>.</value>
        public string History { get; set; }

        /// <summary>The path to the Import folder.</summary>
        /// <value>An absolute path to the <c>Import</c> subdirectory under <see cref="AppDataRoot"/>.</value>
        public string Import { get; set; }

        /// <summary>The path to the Log folder.</summary>
        /// <value>An absolute path to the <c>Log</c> subdirectory under <see cref="AppDataRoot"/>.</value>
        public string Log { get; set; }

        /// <summary>The path to the OptObjErrorMessage folder.</summary>
        /// <value>An absolute path to the <c>OptObjErrorMessage</c> subdirectory under <see cref="AppDataRoot"/>.</value>
        public string OptObjErrorMessage { get; set; }

        /// <summary>The path to the TranslationTable folder.</summary>
        /// <value>An absolute path to the <c>TranslationTable</c> subdirectory under <see cref="AppDataRoot"/>.</value>
        public string TranslationTable { get; set; }

        /// <summary>The path to the archive root folder.</summary>
        /// <value>An absolute path to the <c>Archive</c> subdirectory under <see cref="DataRoot"/>.</value>
        public string ArchiveRoot { get; set; }

        /// <summary>The path to the session-specific folder.</summary>
        /// <value>An absolute path scoped to the current user, session date, and session start time.</value>
        public string Session { get; set; }

        /// <summary>Creates a fully populated <see cref="TngnWsvcDataFolders"/> instance for the given session context.</summary>
        /// <remarks>
        /// All paths are constructed as absolute paths rooted at <paramref name="serverDataPath"/> and the
        /// supplied <paramref name="avatarSystem"/>.
        /// </remarks>
        /// <param name="avatarSystem">The name of the Avatar system, used as a subfolder under <paramref name="serverDataPath"/>.</param>
        /// <param name="avatarUserId">The Avatar user ID, used to scope the session path to a specific user.</param>
        /// <param name="serverDataPath">The root server data path from which all folder paths are derived.</param>
        /// <param name="sessionDate">The date of the session, used as a subfolder in the session path.</param>
        /// <param name="sessionStartTime">The start time of the session, used as the innermost subfolder in the session path.</param>
        /// <returns>A new <see cref="TngnWsvcDataFolders"/> instance with all folder paths populated.</returns>
        /// <example>
        /// <code>
        /// var folders = TngnWsvcDataFolders.Load(
        ///     avatarSystem:     "LIVE",
        ///     avatarUserId:     "jsmith",
        ///     serverDataPath:   @"C:\Tingen_Data",
        ///     sessionDate:      "2026-05-15",
        ///     sessionStartTime: "103045");
        ///
        /// Console.WriteLine(folders.DataRoot);
        /// // Output: C:\Tingen_Data\LIVE
        ///
        /// Console.WriteLine(folders.AppDataRoot);
        /// // Output: C:\Tingen_Data\LIVE\AppData
        ///
        /// Console.WriteLine(folders.Session);
        /// // Output: C:\Tingen_Data\LIVE\Session\2026-05-15\jsmith\103045
        /// </code>
        /// </example>
        internal static TngnWsvcDataFolders Load(string avatarSystem, string avatarUserId, string serverDataPath, string sessionDate, string sessionStartTime)
        {
            return new TngnWsvcDataFolders
            {
                AvatarGeneratedData = $@"{serverDataPath}\AvatarGeneratedData",
                DataRoot            = $@"{serverDataPath}\{avatarSystem}",
                AppDataRoot         = $@"{serverDataPath}\{avatarSystem}\AppData",
                Blueprint           = $@"{serverDataPath}\{avatarSystem}\AppData\Blueprint",
                Config              = $@"{serverDataPath}\{avatarSystem}\AppData\Config",
                Export              = $@"{serverDataPath}\{avatarSystem}\AppData\Export",
                History             = $@"{serverDataPath}\{avatarSystem}\AppData\History",
                Import              = $@"{serverDataPath}\{avatarSystem}\AppData\Import",
                Log                 = $@"{serverDataPath}\{avatarSystem}\AppData\Log",
                OptObjErrorMessage  = $@"{serverDataPath}\{avatarSystem}\AppData\OptObjErrorMessage",
                TranslationTable    = $@"{serverDataPath}\{avatarSystem}\AppData\TranslationTable",
                ArchiveRoot         = $@"{serverDataPath}\{avatarSystem}\Archive",
                Session             = $@"{serverDataPath}\{avatarSystem}\Session\{sessionDate}\{avatarUserId}\{sessionStartTime}"
            };
        }
    }
}