// 260728_code
// 260727_documentation

using System;

namespace TingenWebService.Trove
{
    /// <summary>User-modifiable templates.</summary>
    /// <remarks>
    /// <note type="note" title="About blueprints">
    /// Blueprints are essentially templates for output generated by the Tingen Web Service. They are used to format
    /// logs,error messages, and other data in a consistent manner.<br/>
    /// <br/>
    /// When the Tingen Web Service is initialized, these templates are exported to the <c>blueprints\</c> folder.
    /// The external templates can then be modified by the user to customize the log output.
    /// </note>
    /// <note type="tip" title="Restoring blueprints">
    /// To restore a template to its original state, delete the template file from the blueprints folder and restart the
    /// Tingen Web Service. The original template will be copied back to the blueprints folder.
    /// </note>
    /// </remarks>
    internal static class Blueprint
    {
        /// <summary>Build the error log template.</summary>
        /// <returns>The error log template string.</returns>
        internal static string ErrorLogBlueprint() =>
            $"================================================================================{Environment.NewLine}" +
            $"Tingen Web Service Error Log{Environment.NewLine}" +
            $"Date/Time: ~SESSION~DATE~TIME~{Environment.NewLine}" +
            $"================================================================================{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"[Error code] ~ERROR~CODE~{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"~LOG~MESSAGE~{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"--------------------------------------------------------------------------------{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"[ASSEMBLY] ~ASSEMBLY~{Environment.NewLine}" +
            $"[CLASS] ~CLASS~{Environment.NewLine}" +
            $"[METHOD] ~METHOD~{Environment.NewLine}" +
            $"[LINE] ~LINE~{Environment.NewLine}";

        /// <summary>Build the critical error log template.</summary>
        /// <returns>The critical error log template string.</returns>
        internal static string CriticalErrorLogBlueprint() =>
            $"================================================================================{Environment.NewLine}" +
            $"Tingen Web Service Critical Error Log{Environment.NewLine}" +
            $"Date/Time: ~SESSION~DATE~TIME~{Environment.NewLine}" +
            $"================================================================================{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"[Error code] ~ERROR~CODE~{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"~LOG~MESSAGE~{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"--------------------------------------------------------------------------------{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"[ASSEMBLY] ~ASSEMBLY~{Environment.NewLine}" +
            $"[CLASS] ~CLASS~{Environment.NewLine}" +
            $"[METHOD] ~METHOD~{Environment.NewLine}" +
            $"[LINE] ~LINE~{Environment.NewLine}";

        /// <summary>Build the session log template.</summary>
        /// <returns>The session log template string.</returns>
        internal static string SessionLogBlueprint() =>
            $"================================================================================{Environment.NewLine}" +
            $"Tingen Web Service Session Log                               [~RELEASE~BUILD~]  {Environment.NewLine}" +
            $"--------------------------------------------------------------------------------{Environment.NewLine}" +
            $"            Date: ~SESSION~DATE~{Environment.NewLine}" +
            $"           Start: ~SESSION~START~{Environment.NewLine}" +
            $"             End: ~SESSION~END~{Environment.NewLine}" +
            $"        Duration: ~SESSION~DURATION~{Environment.NewLine}" +
            $"    Logged in as: ~AVATAR~USER~NAME~{Environment.NewLine}" +
            $"   Avatar system: ~AVATAR~SYSTEM~{Environment.NewLine}" +
            $"Script parameter: ~SCRIPT~PARAMETER~{Environment.NewLine}" +
            $"================================================================================{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"--------------{Environment.NewLine}" +
            $"Session Detail{Environment.NewLine}" +
            $"--------------{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"~SESSION~RUNNING~LOG~";
    }
}