// 260725_code
// 260727_documentation

/* About blueprints
 * ================
 * Blueprints are essentially templates for output generated by the Tingen Web Service. They are used to format logs,
 * error messages, and other data in a consistent manner.
 * 
 * Blueprints are exported to the "Tingen_Data\WebService\%AvatarSystem%\Blueprints" folder when the Tingen Web Service
 * is initialized. Users can modify these templates to customize the output.
 *
 */


using System;

namespace TingenWebService.Trove
{
    /// <summary>Tingen Web Service blueprints.</summary>
    /// <remarks>
    /// <note type="important" title="About blueprints">
    /// Blueprints are essentially templates for output generated by the Tingen Web Service. They are used to format
    /// logs, When the Tingen Web Service is initialized, these templates are exported to the blueprints folder. The
    /// external templates can then be modified by the user to customize the log output.<br> <br>To restore a template
    /// to its original state, delete the template file from the blueprints folder and restart the Tingen Web Service.
    /// The original template will be copied back to the blueprints folder.
    /// </note>
    /// </remarks>
    internal static class Blueprint
    {
        internal static string ErrorLogBlueprint() =>
            $"================================================================================{Environment.NewLine}" +
            $"Tingen Web Service Error Log{Environment.NewLine}" +
            $"Date/Time: ~SESSION~DATE~TIME~{Environment.NewLine}" +
            $"================================================================================{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"[Error code] ~ERROR~CODE~{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"~LOG~MESSAGE~{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"--------------------------------------------------------------------------------{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"[ASSEMBLY] ~ASSEMBLY~{Environment.NewLine}" +
            $"[CLASS] ~CLASS~{Environment.NewLine}" +
            $"[METHOD] ~METHOD~{Environment.NewLine}" +
            $"[LINE] ~LINE~{Environment.NewLine}";

        internal static string CriticalErrorLogBlueprint() =>
            $"================================================================================{Environment.NewLine}" +
            $"Tingen Web Service Critical Error Log{Environment.NewLine}" +
            $"Date/Time: ~SESSION~DATE~TIME~{Environment.NewLine}" +
            $"================================================================================{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"[Error code] ~ERROR~CODE~{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"~LOG~MESSAGE~{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"--------------------------------------------------------------------------------{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"[ASSEMBLY] ~ASSEMBLY~{Environment.NewLine}" +
            $"[CLASS] ~CLASS~{Environment.NewLine}" +
            $"[METHOD] ~METHOD~{Environment.NewLine}" +
            $"[LINE] ~LINE~{Environment.NewLine}";

        internal static string SessionLogBlueprint() =>
            $"================================================================================{Environment.NewLine}" +
            $"Tingen Web Service Session Log                               [~RELEASE~BUILD~]  {Environment.NewLine}" +
            $"--------------------------------------------------------------------------------{Environment.NewLine}" +
            $"            Date: ~SESSION~DATE~{Environment.NewLine}" +
            $"           Start: ~SESSION~START~{Environment.NewLine}" +
            $"             End: ~SESSION~END~{Environment.NewLine}" +
            $"        Duration: ~SESSION~DURATION~{Environment.NewLine}" +
            $"    Logged in as: ~AVATAR~USER~NAME~{Environment.NewLine}" +
            $"   Avatar system: ~AVATAR~SYSTEM~{Environment.NewLine}" +
            $"Script parameter: ~SCRIPT~PARAMETER~{Environment.NewLine}" +
            $"================================================================================{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"--------------{Environment.NewLine}" +
            $"Session Detail{Environment.NewLine}" +
            $"--------------{Environment.NewLine}" +
            $"{Environment.NewLine}" +
            $"~SESSION~DETAILS~";

        //NOT USED
        //internal static string OptObjUnknownParameterBlueprint() =>
        //    "Unknown parameter: ~COMMAND~ [v~VERSION~ e~ERROR~CODE~]";
    }
}