// 260729_code
// 260729_documentation

using System;
using System.IO;
using TingenWebService.Core.Logger;
using TingenWebService.Core.Trove;

namespace TingenWebService.Core.Framework
{
    /// <summary>Framework logic.</summary>
    /// <remarks>
    /// TBD
    /// </remarks>
    internal class FrameworkConfiguration
    {
        /// <summary>Avatar generated data.</summary>
        /// <remarks>
        /// Any data that is generated by Avatar is stored here.
        /// </remarks>
        public string AvatarGeneratedDataRoot { get; set; }

        /// <summary>Configuration data.</summary>
        /// <remarks>
        /// All *.config files are stored here.<br>
        /// </br>
        /// Please note that this folder is available to all Tingen Web Services.
        /// </remarks>
        public string ConfigRoot { get; set; }

        /// <summary>Export data.</summary>
        /// <remarks>
        /// All exported data is stored here.
        /// </remarks>
        public string ExportRoot { get; set; }

        /// <summary>Import data.</summary>
        /// <remarks>
        /// All imported data is stored here.
        /// </remarks>
        public string ImportRoot { get; set; }

        /// <summary>Log data.</summary>
        /// <remarks>
        /// All system logs are stored here.
        /// </remarks>
        public string SysLogRoot { get; set; }

        /// <summary>Blueprint data.</summary>
        /// <remarks>
        /// All blueprint data is stored here.
        /// </remarks>
        public string BlueprintRoot { get; set; }

        /// <summary>Session data.</summary>
        /// <remarks>
        /// All session data is stored here.
        /// </remarks>
        public string SessionRoot { get; set; }

        /// <summary>Translation table data.</summary>
        /// <remarks>
        /// All translation table data is stored here.
        /// </remarks>
        public string TranslationTableRoot { get; set; }

        /// <summary>Load the Tingen Web Service framework.</summary>
        /// <param name="hostDataPath">The root path for data storage.</param>
        /// <param name="avatarSystem">The avatar system identifier.</param>
        /// <returns>A <see cref="FrameworkConfiguration"/> instance with the specified paths.</returns>
        /// 

        internal static FrameworkConfiguration Load(string dataRoot, string avatarSystem)
        {
            try
            {
                return Build(dataRoot, avatarSystem);
            }
            catch (Exception ex)
            {
                LogEvent.Primeval("ERR-FrameworkConfiguration", SysMsg.ERR1120(ex.Message)[1]);

                throw;
            }
        }

        internal static FrameworkConfiguration Build(string hostDataPath, string avatarSystem)
        {
            /* For debugging prior to logging functionality being initialized.
             * Disable in production.
             */
            //Logger.LogEvent.Primeval("LoadFramework");

            return new FrameworkConfiguration()
            {
                AvatarGeneratedDataRoot = Path.Combine(hostDataPath, "WebService", "AvatarGeneratedData"),
                ConfigRoot              = Path.Combine(hostDataPath, "WebService", avatarSystem, "Config"),
                ExportRoot              = Path.Combine(hostDataPath, "WebService", avatarSystem, "Export"),
                ImportRoot              = Path.Combine(hostDataPath, "WebService", avatarSystem, "Import"),
                SysLogRoot              = Path.Combine(hostDataPath, "WebService", avatarSystem, "SysLog"),
                BlueprintRoot           = Path.Combine(hostDataPath, "WebService", avatarSystem, "Blueprints"),
                SessionRoot             = Path.Combine(hostDataPath, "WebService", avatarSystem, "Session"),
                TranslationTableRoot    = Path.Combine(hostDataPath, "WebService", avatarSystem, "TranslationTables")
            };
        }
    }
}