// 260804_code
// 260729_documentation

using System;
using System.IO;
using TingenWebService.Core.Logger;
using TingenWebService.Core.Trove;

namespace TingenWebService.Core.Framework
{
    /// <summary>Framework logic.</summary>
    /// <remarks>TBD</remarks>
    internal class FrameworkConfig
    {
        /// <summary>Avatar generated data.</summary>
        /// <remarks>
        /// Any data that is generated by Avatar is stored here.<br/>
        /// This folder is available to all Tingen Web Services.
        /// </remarks>
        public string AvatarGeneratedDataRoot { get; set; }

        /// <summary>Configuration data.</summary>
        /// <remarks>
        /// All *.config files are stored here.<br>
        /// </br>
        /// Please note that 
        /// </remarks>
        public string ConfigRoot { get; set; }

        /// <summary>Export data.</summary>
        /// <remarks>All exported data is stored here.</remarks>
        public string ExportRoot { get; set; }

        /// <summary>Import data.</summary>
        /// <remarks>All imported data is stored here.</remarks>
        public string ImportRoot { get; set; }

        /// <summary>Log data.</summary>
        /// <remarks>All system logs are stored here.</remarks>
        public string SysLogRoot { get; set; }

        /// <summary>Blueprint data.</summary>
        /// <remarks> All blueprint data is stored here.</remarks>
        public string BlueprintRoot { get; set; }

        /// <summary>Session data.</summary>
        /// <remarks>All session data is stored here.</remarks>
        public string SessionRoot { get; set; }

        /// <summary>Translation table data.</summary>
        /// <remarks>All translation table data is stored here.</remarks>
        public string TranslationTableRoot { get; set; }

        /// <summary>Load the Tingen Web Service framework.</summary>
        /// <param name="dataRoot">The root path for data storage.</param>
        /// <param name="avatarSystem">The avatar system identifier.</param>
        /// <returns>A <see cref="FrameworkConfig"/> instance with the specified paths.</returns>
        internal static FrameworkConfig Load(string dataRoot, string avatarSystem)
        {
            //LogEvent.Primeval("PRELOG-TRACE-FrwkConfig-Load");

            try
            {
                return Build(dataRoot, avatarSystem);
            }
            catch (Exception ex)
            {
                LogEvent.Primeval("ERR1120_TwsConfigLoadFailed", SysMsg.ERR1120(ex.Message)[1]);

                throw;
            }
        }

        /// <summary>Build a <see cref="FrameworkConfig"/> instance with the specified paths.</summary>
        /// <param name="dataRoot">The root path for data storage.</param>
        /// <param name="avatarSystem">The avatar system identifier.</param>
        /// <returns>A <see cref="FrameworkConfig"/> instance with the specified paths.</returns>
        internal static FrameworkConfig Build(string dataRoot, string avatarSystem)
        {
            //LogEvent.Primeval("PRELOG-TRACE-FrwkConfig-Build");

            var wsvcRoot         = Path.Combine(dataRoot, "WebService");
            var avatarSystemRoot = Path.Combine(wsvcRoot, avatarSystem);

            return new FrameworkConfig()
            {
                AvatarGeneratedDataRoot = Path.Combine(wsvcRoot, "AvatarGeneratedData"),
                ConfigRoot              = Path.Combine(avatarSystemRoot, "Config"),
                ExportRoot              = Path.Combine(avatarSystemRoot, "Export"),
                ImportRoot              = Path.Combine(avatarSystemRoot, "Import"),
                SysLogRoot              = Path.Combine(avatarSystemRoot, "SysLog"),
                BlueprintRoot           = Path.Combine(avatarSystemRoot, "Blueprints"),
                SessionRoot             = Path.Combine(avatarSystemRoot, "Session"),
                TranslationTableRoot    = Path.Combine(avatarSystemRoot, "TranslationTables")
            };
        }
    }
}