// 260725_code
// 260726_documentation

using System;
using System.IO;
using TingenWebService.Du;
using TingenWebService.Trove;

namespace TingenWebService.Core
{
    /// <summary>Framework logic.</summary>
    /// <remarks>
    /// TBD
    /// </remarks>
    internal class Framework
    {
        /// <summary>Avatar generated data.</summary>
        /// <remarks>
        /// Any data that is generated by Avatar is stored here.
        /// </remarks>
        public string AvatarGeneratedDataRoot { get; set; }

        /// <summary>Configuration data.</summary>
        /// <remarks>
        /// All *.config files are stored here.<br>
        /// </br>
        /// Please note that this folder is available to all Tingen Web Services.
        /// </remarks>
        public string ConfigRoot { get; set; }

        /// <summary>Export data.</summary>
        /// <remarks>
        /// All exported data is stored here.
        /// </remarks>
        public string ExportRoot { get; set; }

        /// <summary>Import data.</summary>
        /// <remarks>
        /// All imported data is stored here.
        /// </remarks>
        public string ImportRoot { get; set; }

        /// <summary>Log data.</summary>
        /// <remarks>
        /// All system logs are stored here.
        /// </remarks>
        public string SysLogRoot { get; set; }

        /// <summary>Blueprint data.</summary>
        /// <remarks>
        /// All blueprint data is stored here.
        /// </remarks>
        public string BlueprintRoot { get; set; }

        /// <summary>Session data.</summary>
        /// <remarks>
        /// All session data is stored here.
        /// </remarks>
        public string SessionRoot { get; set; }

        /// <summary>Translation table data.</summary>
        /// <remarks>
        /// All translation table data is stored here.
        /// </remarks>
        public string TranslationTableRoot { get; set; }

        /// <summary>Load the Tingen Web Service framework.</summary>
        /// <param name="hostDataPath">The root path for data storage.</param>
        /// <param name="avatarSystem">The avatar system identifier.</param>
        /// <returns>A <see cref="Framework"/> instance with the specified paths.</returns>
        internal static Framework Load(string hostDataPath, string avatarSystem)
        {
            /* For debugging prior to logging functionality being initialized.
             * Disable in production.
             */
            //LogEvent.Primeval("LoadFramework");

            return new Framework()
            {
                AvatarGeneratedDataRoot = Path.Combine(hostDataPath, "WebService", "AvatarGeneratedData"),
                ConfigRoot              = Path.Combine(hostDataPath, "WebService", avatarSystem, "Config"),
                ExportRoot              = Path.Combine(hostDataPath, "WebService", avatarSystem, "Export"),
                ImportRoot              = Path.Combine(hostDataPath, "WebService", avatarSystem, "Import"),
                SysLogRoot              = Path.Combine(hostDataPath, "WebService", avatarSystem, "SysLog"),
                BlueprintRoot           = Path.Combine(hostDataPath, "WebService", avatarSystem, "Blueprints"),
                SessionRoot             = Path.Combine(hostDataPath, "WebService", avatarSystem, "Session"),
                TranslationTableRoot    = Path.Combine(hostDataPath, "WebService", avatarSystem, "TranslationTables")
            };
        }

        /// <summary>Verify the Tingen Web Service framework.</summary>
        /// <param name="twsFramework">The framework instance containing the paths to verify.</param>
        /// <remarks>
        /// The framework is verified daily.
        /// </remarks>
        internal static void Verify(Framework twsFramework)
        {
            /* For debugging prior to logging functionality being initialized.
             * Disable in production.
             */
            //LogEvent.Primeval("VerifyFrameworkComponents");

            foreach (var path in Catalog.FrameworkPathList(twsFramework))
            {
                try
                {
                    DuDirectory.EnsureDirectoryExists(path);
                }
                catch (Exception ex)
                {
                    /* Use a primeval log to log the error, since the logging functionality is not initialized yet.
                     */
                    Logger.LogEvent.Primeval("[CR7622]Framework", Epistle.Error7622(path, ex.Message));
                    //TODO - Should probably send an email notification.
                }
            }
        }

        /// <summary>Exports all blueprint templates to the specified host directory.</summary>
        /// <param name="blueprintRoot">The root directory where the blueprints will be exported.</param>
        internal static void ExportBlueprints(string blueprintRoot)
        {
            /* For debugging prior to logging functionality being initialized.
             * Disable in production.
             */
            //LogEvent.Primeval("ExportBlueprints");

            // TODO - There is a better way to do this.

            var errorLogBlueprintPath = Path.Combine(blueprintRoot, "ErrorLog.blueprint");

            if (!File.Exists(errorLogBlueprintPath))
            {
                DuFile.DeadDrop(errorLogBlueprintPath, Blueprint.ErrorLogBlueprint());
            }

            var criticalErrorLogBlueprintPath = Path.Combine(blueprintRoot, "CriticalErrorLog.blueprint");

            if (!File.Exists(criticalErrorLogBlueprintPath))
            {
                DuFile.DeadDrop(criticalErrorLogBlueprintPath, Blueprint.CriticalErrorLogBlueprint());
            }

            var sessionLogBlueprintPath = Path.Combine(blueprintRoot, "SessionLog.blueprint");

            if (!File.Exists(sessionLogBlueprintPath))
            {
                DuFile.DeadDrop(sessionLogBlueprintPath, Blueprint.SessionLogBlueprint());
            }

            //var unknownParameterLogBlueprintPath = Path.Combine(blueprintRoot, "UnknownParameterLog.blueprint");

            //if (!File.Exists(unknownParameterLogBlueprintPath))
            //{
            //    DuFile.DeadDrop(Path.Combine(blueprintRoot, "UnknownParameterLog.blueprint"), Blueprint.OptObjUnknownParameterBlueprint());
            //}
        }
    }
}