exclude:
  - appendix/
  - dev/
  - glossary/
  - man/
  - rn/
  - CHANGELOG.md
  - CODEOWNERS
  - CONTRIBUTORS.md
  - DEVELOPMENT.md
  - FAQ.md
  - KNOWN-ISSUES.md
  - NOTICES.md
  - ROADMAP.md
  - SECURITY.md
  - SUPPORT.md
  - TROUBLESHOOTING.md